# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "6278a019783afb6e4c45e4c4bf881f4c"
name = "app-ui"
handle = "app-ui-4"
application_url = "https://shopify-first-app-qlo0.onrender.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "gmr-test-data.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_cart_transforms,write_payment_customizations,write_products"

[auth]
redirect_urls = [
  "https://shopify-first-app-qlo0.onrender.com/auth/callback",
  "https://shopify-first-app-qlo0.onrender.com/auth/shopify/callback",
  "https://shopify-first-app-qlo0.onrender.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"

[pos]
embedded = false
